# FESTIM Model Configuration
model_parameters:
  total_time: 25.0  # [s]
  T_0: 300.0  # initial temperature [K]
  transient: False  # enable transient simulation
  heat_model: 'none'  # type of heat model to use, options: 'heat_transfer', 'none'

geometry:
  length: 3.5e-4 # [m]

materials:

  material_name: "Li2O"
  # diffusivity: 4.1e-7  # [m²/s]
  # solubility: 1.87e24  # [H/m³/Pa^0.5]
  D_0: 1.03613e-6  # diffusion coefficient [m²/s]
  E_D: 0.9028    # activation energy [eV]
  rho: 534.0  # density [kg/m³]
  heat_capacity: 900.0  # specific heat capacity [J/(kg*K)]
  #h_coeff: 100.0  # convective heat transfer coefficient [W/( m²*K)]
  thermal_conductivity: 2.0  # thermal conductivity [W/(m*K)]
  
  
simulation:
  n_elements: 1024  # number of mesh elements

  time_step: 0.05      # [s]
  max_stepsize: 0.1   # [s]
  stepsize_change_ratio: 1.1

  absolute_tolerance: 1.0e+10
  relative_tolerance: 1.0e-10

  output_directory: "results/"
  milestone_times: [0.1, 0.2, 0.5, 1.0, 5.0, 10.0, 25.0] # times at which results are saved [s]

boundary_conditions: 
  left_bc_type: "neumann"
  left_bc_value: 0.0 # this means no flux at the left boundary

  right_bc_type: "dirichlet" 
  right_bc_value: 1.0e15 # this means a fixed concentration at the right boundary

source_terms: # Tritium source terms either directly specified or calculated from neutron flux

# field 0 = tritium concentration
# field 1 = heat source term

  source_type: "constant"
  source_value: 1.0e20  # source term value in [m3]

  n_flux: 1e18 # [n/m²/s] 
  t_yield : 1.0e-6  # t atoms per neutron 

  T_source : n_flux * t_yield  # tritium source term [H/m3/s]

  source_type_heat: "constant"
  source_value_heat: 1.0e+3  # constant heat source term value in [W/m³]

  # source_type: "xdmf"  # use XDMF file for source term for a neutron flux distribution of tallies from a neutron transport code
  source_type: xdmf
  xdmf_file: Salome/Meshes/salome_mesh_with_source.xdmf"
  xdmf_dataset_name: "source"  # match dataset name in the XDMF


# END OF CONFIGURATION FILE