# FESTIM Model Configuration
model_parameters:
  total_time: 100.0  # s
  T_0: 300.0  # initial temperature in [K]
  #T_ext: 300.0  # external temperature in [K]
  'heat_model': 'heat_transfer'  # type of heat model to use, options: 'heat_transfer', 'none'
  transient: True  # enable transient simulation
  
geometry:
  length: 3.5e-5 #3.5e-6 #0.000007    # [m]
  #thickness: 1.0e-6   # [m]

materials:

  # material_name: "Lithium"
  # diffusivity: 4.1e-7  # [m²/s]
  # solubility: 1.87e24  # [H/m³/Pa^0.5]
  D_0: 1.0e-6 #4.1e-7  # diffusion coefficient in [m²/s]
  E_D: 0.2 #0.39    # activation energy in [eV]
  thermal_conductivity: 33.0  # thermal conductivity in [W/(m*K)]
  rho: 1000.0 #534.0  # density in [kg/m³]
  heat_capacity: 100.0  # specific heat capacity in [J/(kg*K)]
  #h_coeff: 100.0  # convective heat transfer coefficient in [W/(m²*K)]
  
simulation:
  n_elements: 1024  # number of mesh elements

  time_step: 0.05      # s
  max_stepsize: 0.1   # s
  stepsize_change_ratio: 1.1

  absolute_tolerance: 1.0e+10
  relative_tolerance: 1.0e-10

  output_directory: "results/"
  milestone_times: [0.1, 0.2, 0.5, 1.0, 5.0, 10.0, 25.0] # times at which results are saved [s]

boundary_conditions:

  left_bc_concentration_type: "neumann"
  left_bc_concentration_value: 0.0

  right_bc_concentration_type: "dirichlet"
  right_bc_concentration_value: 1.0e15

  left_bc_heat_type: "dirichlet"
  left_bc_T_value: 300.0  # external temperature in [K]

  right_bc_heat_type: "neumann"
  right_bc_T_value: 650.0  # external temperature in [K]  
  right_bc_hcoeff_value: 100.0  # convective heat transfer coefficient in [W/(m²*K)]

source_terms:

  source_concentration_type: "constant"
  source_concentration_value: 1.0e20  # source term value in [m^-3]

  source_heat_type: "constant"
  source_heat_value: 1.0e+3 # constant heat source term value in [W/m³]


# END OF CONFIGURATION FILE