# FESTIM Model Configuration
model_parameters:
  total_time: 100.0  # s
  T_0: 300.0  # initial temperature in [K]
  #T_ext: 300.0  # external temperature in [K]
  heat_model: 'heat_transfer'  # type of heat model to use, options: 'heat_transfer', 'none'
  transient: True  # enable transient simulation
  
geometry:
  coordinate_system: "cartesian" # "spherical" # coordinate system used in the simulation
  length: 3.5e-7 #3.5e-6 #0.000007 # [m]
  #thickness: 1.0e-6   # [m]

materials:

  # material_name: "Lithium"
  # diffusivity: 4.1e-7  # [m²/s]
  # solubility: 1.87e24  # [H/m³/Pa^0.5]
  D_0: 1.0e-6 #4.1e-7  # diffusion coefficient in [m²/s]
  E_D: 0.2 #0.39    # activation energy in [eV]
  thermal_conductivity: 33.0  # thermal conductivity in [W/(m*K)] # Li2O >=66.
  rho: 1000.0 #534.0  # density in [kg/m³] # Li2O ~2000.
  heat_capacity: 100.0  # specific heat capacity in [J/(kg*K)] # Li2O >=1000.
  #h_coeff: 100.0  # convective heat transfer coefficient in [W/(m²*K)]
  
simulation:
  n_elements: 1024  # number of mesh elements

  time_step: 0.05      # s
  max_stepsize: 0.1   # s
  stepsize_change_ratio: 1.1

  absolute_tolerance: 1.0e+10
  relative_tolerance: 1.0e-10

  output_directory: "results/"
  milestone_times: [0.1, 0.2, 0.5, 1.0, 5.0, 10.0, 25.0] # times at which results are saved [s]

boundary_conditions:

  concentration:
    left:
      type: "neumann"
      value: 0.0
    right:
      type: "dirichlet"
      value: 1.0e15

  temperature:
    left:
      type: "dirichlet"
      value: 300.0  # external temperature in [K]
    right:
      type: "convective_flux"
      Text_value: 650.0  # external temperature in [K]  
      hcoeff_value: 100.0  # convective heat transfer coefficient in [W/(m²*K)]

source_terms:

  concentration:
    source_type: "constant"
    source_value: 1.0e20  # source term value in [m^-3]

  heat:
    source_type: "constant"
    source_value: 1.0e+3 # constant heat source term value in [W/m³]


# END OF CONFIGURATION FILE