# FESTIM Model Configuration
model_parameters:
  total_time: 25.0  # [s]
  T_0: 300.0  # initial temperature [K]

geometry:
  length: 3.5e-4 # [m]

materials:

  material_name: "Li2O"
  # diffusivity: 4.1e-7  # [m²/s]
  # solubility: 1.87e24  # [H/m³/Pa^0.5]
  D_0: 1.03613e-6  # diffusion coefficient [m²/s]
  E_D: 0.9028    # activation energy [eV]
  
simulation:
  n_elements: 1024  # number of mesh elements

  time_step: 0.05      # [s]
  max_stepsize: 0.1   # [s]
  stepsize_change_ratio: 1.1

  absolute_tolerance: 1.0e+10
  relative_tolerance: 1.0e-10

  output_directory: "results/"
  milestone_times: [0.1, 0.2, 0.5, 1.0, 5.0, 10.0, 25.0] # times at which results are saved [s]

boundary_conditions:
  left_bc_type: "neumann"
  left_bc_value: 0.0

  right_bc_type: "dirichlet"
  right_bc_value: 1.0e15

source_terms:
  source_type: "constant"
  source_value: 1.0e20  # source term value in [m^-3]

# END OF CONFIGURATION FILE