# FESTIM Model Configuration
model_parameters:
  total_time: 100.0  # [s]
  T_0: 900.0 #300.0 #600.0 #300.0  # initial temperature [K]
  transient: False  # enable transient simulation
  heat_model: 'none'  # type of heat model to use, options: 'heat_transfer', 'none'

geometry:
  coordinate_system: "spherical" #"cartesian"  # coordinate system type, options: 'cartesian', 'cylindrical', 'spherical'
  length: 3.5e-3 #3.5e-7 #3.5e-4 # [m]

materials:

  material_name: "Li2O"
  # diffusivity: 4.1e-7  # [m²/s]
  # solubility: 1.87e24  # [H/m³/Pa^0.5]
  D_0: 1.03613e-6  # diffusion coefficient [m²/s]
  E_D: 0.9028    # activation energy [eV]
  rho: 534.0  # density [kg/m³]
  heat_capacity: 900.0  # specific heat capacity [J/(kg*K)]
  #h_coeff: 100.0  # convective heat transfer coefficient [W/( m²*K)]
  thermal_conductivity: 2.0  # thermal conductivity [W/(m*K)]
  
  
simulation:
  n_elements: 2024  # number of mesh elements

  time_step: 0.05      # [s]
  max_stepsize: 0.1   # [s]
  stepsize_change_ratio: 1.1

  absolute_tolerance: 1.0e+10
  relative_tolerance: 1.0e-10

  output_directory: "results/"
  milestone_times: [0.1, 0.2, 0.5, 1.0, 5.0, 10.0, 25.0] # times at which results are saved [s]

boundary_conditions:
  left_bc_concentration_type: "neumann"
  left_bc_concentration_value: 0.0

  right_bc_concentration_type: "dirichlet"
  right_bc_concentration_value: 1.0e17 #1.0e15 # right boundary concentration [H/m³]

source_terms:

  source_concentration_type: "constant"
  source_concentration_value: 1.0e18 #1.0e17 #1.0e20  # source term value in [m^-3]

  source_heat_type: "constant"
  source_heat_value: 1.0e+3  # constant heat source term value in [W/m³]

# END OF CONFIGURATION FILE