# FESTIM Model Configuration - for verification tests

model_parameters:
  transient: True
  total_time: 1024.0
  problems:

    tritium_transport:
      species:
        - "Tritium"
      domains:
        - id: 1
        
geometry:
  dimensionality: 1
  coordinate_system: "spherical"
  domains:
    - id: 1
      length: 1.0
      material: 123456789

materials:

  - material_id: 123456789
    material_name: "test_stuff"
    D_0:
      mean: 1.0e-6
      relative_stdev: 0.05
      pdf: 'uniform'
    E_D:
      mean: 1.0
      relative_stdev: 0.1
      abs_stdev: 0.1
      pdf: 'uniform'
    thermal_conductivity: 
      mean: 1.0
      relative_stdev: 0.1
      pdf: 'uniform'
    rho: 
      mean: 1000.0 
    heat_capacity:
      mean: 10000.0

simulation:
  mesh_type: "regular"
  n_elements: 1024

  time_step:
    default_value: 0.01
    time_stepping_type: "fixed"
    max_stepsize: 0.1 
    stepsize_change_ratio: 1.1

  tolerances:
    absolute_tolerance: 
      tritium_transport: 1.0e+6 
    relative_tolerance: 1.0e-6

  log_level: 20

  output_directory: "results/test"
  milestone_times: [
    0.1, 
    0.25,
    0.5, 
    1.0, 
    2.0, 
    4.0,
    8.0,
    16.0,
    32.0,
    64.0,
    128.0,
    256.0,
    512.0,
    1024.0,
    ]

  quantities_of_interest:
    - tritium_concentration
    - heat_flux

boundary_conditions:

  concentration:
    left:
      type: "neumann"
      species: "Tritium"
      value: 
        mean: 0.0
    right:
      type: "dirichlet"
      species: "Tritium"
      value:
        mean: 0.0
        relative_stdev: 0.05
        pdf: 'uniform'

initial_conditions:

  concentration:
    type: "constant"
    domain_id: 1
    value:
      mean: 1.0e+15

source_terms:

  concentration:
    domain_id: 1
    species: "Tritium"
    type: "constant"
    value:
      mean: 0.0

# END OF CONFIGURATION FILE